### ISSUE TITLE
innobackupex -> xtrabackup?

### ISSUE THREAD

**Issue by ghost** [do-community/ubuntu-1604-mysql-backup#1]
Hi!

Thanks for a very useful set of scripts and companion tutorial. I see the scripts use `innobackupex`. This script, however, seems to be [deprecated](https://www.percona.com/doc/percona-xtrabackup/LATEST/manual.html) in favour of `xtrabackup`. Any chance these scripts can be updated to move to `xtrabackup`?

Cheers,
Erwin

**Comment by imchairmanm** [comment]
@erwinw Hey there.

Yeah, I'm going to push an update for this.  At the time I initially wrote this, there wasn't feature parity between the two tools despite what the Percona documentation claimed.  I just took another look and it looks like `xtrabackup` now has all of the functionality that these scripts require at least.  I'm going to update these as well as the [associated article](https://www.digitalocean.com/community/tutorials/how-to-configure-mysql-backups-with-percona-xtrabackup-on-ubuntu-16-04).

Thanks for the heads up!

**Comment by imchairmanm** [comment]
Just merged the changes.  Cheers.

**Comment by ghost** [comment]
Awesome, thanks so much!
